### ISSUE TITLE
Broken insertion for some symbols

### ISSUE THREAD

**Issue by Ndyukov** [metacoma/silverkey#14]
During insertion found that some inserted wrong.
For example:
Property:
name:  web
value: https://192.168.55.1:4343

Inserted:
https^||192.168.55.1^4343

**Comment by metacoma** [comment]
At the moment, silverkey uses xdotool (https://github.com/jordansissel/xdotool) to insert text in current cursor position.

Looks like, this bug related to xdotool and keyboard layout, which configured in Xorg server.

The similar issues:
https://github.com/jordansissel/xdotool/issues/150
https://github.com/jordansissel/xdotool/issues/49

Please try this workaround https://github.com/jordansissel/xdotool/issues/150#issuecomment-313848154

I do not have this problem, the sample from your  case works fine.
My keyboard layout setting:
```
setxkbmap -layout "us,ru" -option grp:switch,grp:caps_toggle
```
