### ISSUE TITLE
Please provide an AppImage for download

### ISSUE THREAD

**Issue by probonopd** [metacoma/silverkey#178]
Please provide an AppImage for download on your GitHub Releases page. `linuxdeployqt` can make one, see https://github.com/probonopd/linuxdeployqt/#using-linuxdeployqt-with-travis-ci for an example. Thanks!

**Comment by metacoma** [comment]
Hey, thanks for tip. 

https://github.com/metacoma/silverkey/releases/tag/beta-release done!

**Comment by probonopd** [comment]
Thank you. Unfortunately I don't see a `Silverkey-4e17be7-x86_64.AppImage` file on https://github.com/metacoma/silverkey. If you add one, I can include it in the AppImageHub central directory of available AppImages. Thanks!

**Comment by metacoma** [comment]
No problem, https://github.com/metacoma/silverkey/releases/download/appimage/Silverkey-4e17be7-x86_64.AppImage it's ok?

**Comment by probonopd** [comment]
Thank you very much.

Getting

```
AppRun: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by /run/firejail/appimage/.appimage-7127/AppRun)
```

Please see https://github.com/AppImage/AppImageKit/wiki/Creating-AppImages#creating-appimages-that-are-compatible-with-many-systems.

**Comment by metacoma** [comment]
Thanks for it @probonopd 
I'll try reproduce it in docker container, please tell me your linux environment (distro/version)?

**Comment by metacoma** [comment]
@probonopd hey again! 
Please take a look, i'm added ubuntu:trusty test in our CI process, tests looks fine!
Binary: https://github.com/metacoma/silverkey/releases/download/beta-release/Silverkey-d95c742-x86_64.AppImage

Can you, please, tests again in your environment? Thanks!

**Comment by probonopd** [comment]
That one is looking good. Thank you!
