### ISSUE TITLE
Investigation to how we can deliver silverkey app

### ISSUE THREAD

**Issue by metacoma** [metacoma/silverkey#30]
The best deliver option is a one native file for each platform without any dependencies, like static build.

Let's try to investigate how we can deliver silverkey app for osx,linux,windows.

**Comment by Konovalov-Nik** [comment]
Regarding Mac OS, QT provides a tool macdeployqt which can build a .dmg distribution with a .app inside containing all runtime dependencies. (It can also just modify an existing app and not package it into a dmg).

Workflow is simple.
1) Build a release version with QT Creator. 
2) Run macdeployqt against an .app artifact (e.x. macdeployqt build-silverkey-qt-Desktop_Qt_5_11_0_clang_64bit-Release/silverkey-qt.app -dmg)

**Comment by metacoma** [comment]
For linux - https://flatpak.org/
